---
service-name: homelane-covid-data

# One of: "worker" (old container is killed before starting new one), "service"
# (default, new containers started before old ones are deleted)
service-type: service

# One of: "direct" (default), "internal" (on VPN only), "cloudflare" (pinned SSL certificate)
access-mode: internal

desired-count: auto

primary-container: service

containers:
  service:
    image: r.homelane.co/homelane:$BUILD_TAG
    environment:
      SPRING_PROFILES_ACTIVE: ecs
    secrets:
      NEW_RELIC_LICENSE_KEY: common/newrelic.license.key
      APM_PROVIDER: common/apm.provider
    healthcheck:
      path: /health
      interval: 30
      timeout: 2
      retries: 5
      start-period: 60 # How long should healthchecks wait to allow for startup time
    cpu_units: 128
    memory: 512
    ports:
      HTTP: 8080
      HEALTH: 8081