/*
 * This file is generated by jOOQ.
 */
package co.homelane.db.jooq.tables.records;


import co.homelane.db.jooq.tables.CovidVaccineStatewise;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record18;
import org.jooq.Row18;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CovidVaccineStatewiseRecord extends TableRecordImpl<CovidVaccineStatewiseRecord> implements Record18<LocalDateTime, String, String, String, String, String, String, String, String, String, String, String, String, String, String, String, String, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>covid_vaccine_statewise.updated_on</code>.
     */
    public CovidVaccineStatewiseRecord setUpdatedOn(LocalDateTime value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>covid_vaccine_statewise.updated_on</code>.
     */
    public LocalDateTime getUpdatedOn() {
        return (LocalDateTime) get(0);
    }

    /**
     * Setter for <code>covid_vaccine_statewise.state</code>.
     */
    public CovidVaccineStatewiseRecord setState(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>covid_vaccine_statewise.state</code>.
     */
    public String getState() {
        return (String) get(1);
    }

    /**
     * Setter for <code>covid_vaccine_statewise.total_doses_administered</code>.
     */
    public CovidVaccineStatewiseRecord setTotalDosesAdministered(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>covid_vaccine_statewise.total_doses_administered</code>.
     */
    public String getTotalDosesAdministered() {
        return (String) get(2);
    }

    /**
     * Setter for <code>covid_vaccine_statewise.total_sessions_conducted</code>.
     */
    public CovidVaccineStatewiseRecord setTotalSessionsConducted(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>covid_vaccine_statewise.total_sessions_conducted</code>.
     */
    public String getTotalSessionsConducted() {
        return (String) get(3);
    }

    /**
     * Setter for <code>covid_vaccine_statewise.total_sites</code>.
     */
    public CovidVaccineStatewiseRecord setTotalSites(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>covid_vaccine_statewise.total_sites</code>.
     */
    public String getTotalSites() {
        return (String) get(4);
    }

    /**
     * Setter for <code>covid_vaccine_statewise.first_dose_administered</code>.
     */
    public CovidVaccineStatewiseRecord setFirstDoseAdministered(String value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>covid_vaccine_statewise.first_dose_administered</code>.
     */
    public String getFirstDoseAdministered() {
        return (String) get(5);
    }

    /**
     * Setter for <code>covid_vaccine_statewise.second_dose_administered</code>.
     */
    public CovidVaccineStatewiseRecord setSecondDoseAdministered(String value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>covid_vaccine_statewise.second_dose_administered</code>.
     */
    public String getSecondDoseAdministered() {
        return (String) get(6);
    }

    /**
     * Setter for <code>covid_vaccine_statewise.male_individuals_vaccinated</code>.
     */
    public CovidVaccineStatewiseRecord setMaleIndividualsVaccinated(String value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>covid_vaccine_statewise.male_individuals_vaccinated</code>.
     */
    public String getMaleIndividualsVaccinated() {
        return (String) get(7);
    }

    /**
     * Setter for <code>covid_vaccine_statewise.female_individuals_vaccinated</code>.
     */
    public CovidVaccineStatewiseRecord setFemaleIndividualsVaccinated(String value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>covid_vaccine_statewise.female_individuals_vaccinated</code>.
     */
    public String getFemaleIndividualsVaccinated() {
        return (String) get(8);
    }

    /**
     * Setter for <code>covid_vaccine_statewise.transgender_individuals_vaccinated</code>.
     */
    public CovidVaccineStatewiseRecord setTransgenderIndividualsVaccinated(String value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>covid_vaccine_statewise.transgender_individuals_vaccinated</code>.
     */
    public String getTransgenderIndividualsVaccinated() {
        return (String) get(9);
    }

    /**
     * Setter for <code>covid_vaccine_statewise.total_covaxin_administered</code>.
     */
    public CovidVaccineStatewiseRecord setTotalCovaxinAdministered(String value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for <code>covid_vaccine_statewise.total_covaxin_administered</code>.
     */
    public String getTotalCovaxinAdministered() {
        return (String) get(10);
    }

    /**
     * Setter for <code>covid_vaccine_statewise.total_covishield_administered</code>.
     */
    public CovidVaccineStatewiseRecord setTotalCovishieldAdministered(String value) {
        set(11, value);
        return this;
    }

    /**
     * Getter for <code>covid_vaccine_statewise.total_covishield_administered</code>.
     */
    public String getTotalCovishieldAdministered() {
        return (String) get(11);
    }

    /**
     * Setter for <code>covid_vaccine_statewise.total_sputnik_v_administered</code>.
     */
    public CovidVaccineStatewiseRecord setTotalSputnikVAdministered(String value) {
        set(12, value);
        return this;
    }

    /**
     * Getter for <code>covid_vaccine_statewise.total_sputnik_v_administered</code>.
     */
    public String getTotalSputnikVAdministered() {
        return (String) get(12);
    }

    /**
     * Setter for <code>covid_vaccine_statewise.aefi</code>.
     */
    public CovidVaccineStatewiseRecord setAefi(String value) {
        set(13, value);
        return this;
    }

    /**
     * Getter for <code>covid_vaccine_statewise.aefi</code>.
     */
    public String getAefi() {
        return (String) get(13);
    }

    /**
     * Setter for <code>covid_vaccine_statewise.age_18_45_years</code>.
     */
    public CovidVaccineStatewiseRecord setAge_18_45Years(String value) {
        set(14, value);
        return this;
    }

    /**
     * Getter for <code>covid_vaccine_statewise.age_18_45_years</code>.
     */
    public String getAge_18_45Years() {
        return (String) get(14);
    }

    /**
     * Setter for <code>covid_vaccine_statewise.age_45_60_years</code>.
     */
    public CovidVaccineStatewiseRecord setAge_45_60Years(String value) {
        set(15, value);
        return this;
    }

    /**
     * Getter for <code>covid_vaccine_statewise.age_45_60_years</code>.
     */
    public String getAge_45_60Years() {
        return (String) get(15);
    }

    /**
     * Setter for <code>covid_vaccine_statewise.age_60_above_years</code>.
     */
    public CovidVaccineStatewiseRecord setAge_60AboveYears(String value) {
        set(16, value);
        return this;
    }

    /**
     * Getter for <code>covid_vaccine_statewise.age_60_above_years</code>.
     */
    public String getAge_60AboveYears() {
        return (String) get(16);
    }

    /**
     * Setter for <code>covid_vaccine_statewise.total_individuals_vaccinated</code>.
     */
    public CovidVaccineStatewiseRecord setTotalIndividualsVaccinated(String value) {
        set(17, value);
        return this;
    }

    /**
     * Getter for <code>covid_vaccine_statewise.total_individuals_vaccinated</code>.
     */
    public String getTotalIndividualsVaccinated() {
        return (String) get(17);
    }

    // -------------------------------------------------------------------------
    // Record18 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row18<LocalDateTime, String, String, String, String, String, String, String, String, String, String, String, String, String, String, String, String, String> fieldsRow() {
        return (Row18) super.fieldsRow();
    }

    @Override
    public Row18<LocalDateTime, String, String, String, String, String, String, String, String, String, String, String, String, String, String, String, String, String> valuesRow() {
        return (Row18) super.valuesRow();
    }

    @Override
    public Field<LocalDateTime> field1() {
        return CovidVaccineStatewise.COVID_VACCINE_STATEWISE.UPDATED_ON;
    }

    @Override
    public Field<String> field2() {
        return CovidVaccineStatewise.COVID_VACCINE_STATEWISE.STATE;
    }

    @Override
    public Field<String> field3() {
        return CovidVaccineStatewise.COVID_VACCINE_STATEWISE.TOTAL_DOSES_ADMINISTERED;
    }

    @Override
    public Field<String> field4() {
        return CovidVaccineStatewise.COVID_VACCINE_STATEWISE.TOTAL_SESSIONS_CONDUCTED;
    }

    @Override
    public Field<String> field5() {
        return CovidVaccineStatewise.COVID_VACCINE_STATEWISE.TOTAL_SITES;
    }

    @Override
    public Field<String> field6() {
        return CovidVaccineStatewise.COVID_VACCINE_STATEWISE.FIRST_DOSE_ADMINISTERED;
    }

    @Override
    public Field<String> field7() {
        return CovidVaccineStatewise.COVID_VACCINE_STATEWISE.SECOND_DOSE_ADMINISTERED;
    }

    @Override
    public Field<String> field8() {
        return CovidVaccineStatewise.COVID_VACCINE_STATEWISE.MALE_INDIVIDUALS_VACCINATED;
    }

    @Override
    public Field<String> field9() {
        return CovidVaccineStatewise.COVID_VACCINE_STATEWISE.FEMALE_INDIVIDUALS_VACCINATED;
    }

    @Override
    public Field<String> field10() {
        return CovidVaccineStatewise.COVID_VACCINE_STATEWISE.TRANSGENDER_INDIVIDUALS_VACCINATED;
    }

    @Override
    public Field<String> field11() {
        return CovidVaccineStatewise.COVID_VACCINE_STATEWISE.TOTAL_COVAXIN_ADMINISTERED;
    }

    @Override
    public Field<String> field12() {
        return CovidVaccineStatewise.COVID_VACCINE_STATEWISE.TOTAL_COVISHIELD_ADMINISTERED;
    }

    @Override
    public Field<String> field13() {
        return CovidVaccineStatewise.COVID_VACCINE_STATEWISE.TOTAL_SPUTNIK_V_ADMINISTERED;
    }

    @Override
    public Field<String> field14() {
        return CovidVaccineStatewise.COVID_VACCINE_STATEWISE.AEFI;
    }

    @Override
    public Field<String> field15() {
        return CovidVaccineStatewise.COVID_VACCINE_STATEWISE.AGE_18_45_YEARS;
    }

    @Override
    public Field<String> field16() {
        return CovidVaccineStatewise.COVID_VACCINE_STATEWISE.AGE_45_60_YEARS;
    }

    @Override
    public Field<String> field17() {
        return CovidVaccineStatewise.COVID_VACCINE_STATEWISE.AGE_60_ABOVE_YEARS;
    }

    @Override
    public Field<String> field18() {
        return CovidVaccineStatewise.COVID_VACCINE_STATEWISE.TOTAL_INDIVIDUALS_VACCINATED;
    }

    @Override
    public LocalDateTime component1() {
        return getUpdatedOn();
    }

    @Override
    public String component2() {
        return getState();
    }

    @Override
    public String component3() {
        return getTotalDosesAdministered();
    }

    @Override
    public String component4() {
        return getTotalSessionsConducted();
    }

    @Override
    public String component5() {
        return getTotalSites();
    }

    @Override
    public String component6() {
        return getFirstDoseAdministered();
    }

    @Override
    public String component7() {
        return getSecondDoseAdministered();
    }

    @Override
    public String component8() {
        return getMaleIndividualsVaccinated();
    }

    @Override
    public String component9() {
        return getFemaleIndividualsVaccinated();
    }

    @Override
    public String component10() {
        return getTransgenderIndividualsVaccinated();
    }

    @Override
    public String component11() {
        return getTotalCovaxinAdministered();
    }

    @Override
    public String component12() {
        return getTotalCovishieldAdministered();
    }

    @Override
    public String component13() {
        return getTotalSputnikVAdministered();
    }

    @Override
    public String component14() {
        return getAefi();
    }

    @Override
    public String component15() {
        return getAge_18_45Years();
    }

    @Override
    public String component16() {
        return getAge_45_60Years();
    }

    @Override
    public String component17() {
        return getAge_60AboveYears();
    }

    @Override
    public String component18() {
        return getTotalIndividualsVaccinated();
    }

    @Override
    public LocalDateTime value1() {
        return getUpdatedOn();
    }

    @Override
    public String value2() {
        return getState();
    }

    @Override
    public String value3() {
        return getTotalDosesAdministered();
    }

    @Override
    public String value4() {
        return getTotalSessionsConducted();
    }

    @Override
    public String value5() {
        return getTotalSites();
    }

    @Override
    public String value6() {
        return getFirstDoseAdministered();
    }

    @Override
    public String value7() {
        return getSecondDoseAdministered();
    }

    @Override
    public String value8() {
        return getMaleIndividualsVaccinated();
    }

    @Override
    public String value9() {
        return getFemaleIndividualsVaccinated();
    }

    @Override
    public String value10() {
        return getTransgenderIndividualsVaccinated();
    }

    @Override
    public String value11() {
        return getTotalCovaxinAdministered();
    }

    @Override
    public String value12() {
        return getTotalCovishieldAdministered();
    }

    @Override
    public String value13() {
        return getTotalSputnikVAdministered();
    }

    @Override
    public String value14() {
        return getAefi();
    }

    @Override
    public String value15() {
        return getAge_18_45Years();
    }

    @Override
    public String value16() {
        return getAge_45_60Years();
    }

    @Override
    public String value17() {
        return getAge_60AboveYears();
    }

    @Override
    public String value18() {
        return getTotalIndividualsVaccinated();
    }

    @Override
    public CovidVaccineStatewiseRecord value1(LocalDateTime value) {
        setUpdatedOn(value);
        return this;
    }

    @Override
    public CovidVaccineStatewiseRecord value2(String value) {
        setState(value);
        return this;
    }

    @Override
    public CovidVaccineStatewiseRecord value3(String value) {
        setTotalDosesAdministered(value);
        return this;
    }

    @Override
    public CovidVaccineStatewiseRecord value4(String value) {
        setTotalSessionsConducted(value);
        return this;
    }

    @Override
    public CovidVaccineStatewiseRecord value5(String value) {
        setTotalSites(value);
        return this;
    }

    @Override
    public CovidVaccineStatewiseRecord value6(String value) {
        setFirstDoseAdministered(value);
        return this;
    }

    @Override
    public CovidVaccineStatewiseRecord value7(String value) {
        setSecondDoseAdministered(value);
        return this;
    }

    @Override
    public CovidVaccineStatewiseRecord value8(String value) {
        setMaleIndividualsVaccinated(value);
        return this;
    }

    @Override
    public CovidVaccineStatewiseRecord value9(String value) {
        setFemaleIndividualsVaccinated(value);
        return this;
    }

    @Override
    public CovidVaccineStatewiseRecord value10(String value) {
        setTransgenderIndividualsVaccinated(value);
        return this;
    }

    @Override
    public CovidVaccineStatewiseRecord value11(String value) {
        setTotalCovaxinAdministered(value);
        return this;
    }

    @Override
    public CovidVaccineStatewiseRecord value12(String value) {
        setTotalCovishieldAdministered(value);
        return this;
    }

    @Override
    public CovidVaccineStatewiseRecord value13(String value) {
        setTotalSputnikVAdministered(value);
        return this;
    }

    @Override
    public CovidVaccineStatewiseRecord value14(String value) {
        setAefi(value);
        return this;
    }

    @Override
    public CovidVaccineStatewiseRecord value15(String value) {
        setAge_18_45Years(value);
        return this;
    }

    @Override
    public CovidVaccineStatewiseRecord value16(String value) {
        setAge_45_60Years(value);
        return this;
    }

    @Override
    public CovidVaccineStatewiseRecord value17(String value) {
        setAge_60AboveYears(value);
        return this;
    }

    @Override
    public CovidVaccineStatewiseRecord value18(String value) {
        setTotalIndividualsVaccinated(value);
        return this;
    }

    @Override
    public CovidVaccineStatewiseRecord values(LocalDateTime value1, String value2, String value3, String value4, String value5, String value6, String value7, String value8, String value9, String value10, String value11, String value12, String value13, String value14, String value15, String value16, String value17, String value18) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        value17(value17);
        value18(value18);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CovidVaccineStatewiseRecord
     */
    public CovidVaccineStatewiseRecord() {
        super(CovidVaccineStatewise.COVID_VACCINE_STATEWISE);
    }

    /**
     * Create a detached, initialised CovidVaccineStatewiseRecord
     */
    public CovidVaccineStatewiseRecord(LocalDateTime updatedOn, String state, String totalDosesAdministered, String totalSessionsConducted, String totalSites, String firstDoseAdministered, String secondDoseAdministered, String maleIndividualsVaccinated, String femaleIndividualsVaccinated, String transgenderIndividualsVaccinated, String totalCovaxinAdministered, String totalCovishieldAdministered, String totalSputnikVAdministered, String aefi, String age_18_45Years, String age_45_60Years, String age_60AboveYears, String totalIndividualsVaccinated) {
        super(CovidVaccineStatewise.COVID_VACCINE_STATEWISE);

        setUpdatedOn(updatedOn);
        setState(state);
        setTotalDosesAdministered(totalDosesAdministered);
        setTotalSessionsConducted(totalSessionsConducted);
        setTotalSites(totalSites);
        setFirstDoseAdministered(firstDoseAdministered);
        setSecondDoseAdministered(secondDoseAdministered);
        setMaleIndividualsVaccinated(maleIndividualsVaccinated);
        setFemaleIndividualsVaccinated(femaleIndividualsVaccinated);
        setTransgenderIndividualsVaccinated(transgenderIndividualsVaccinated);
        setTotalCovaxinAdministered(totalCovaxinAdministered);
        setTotalCovishieldAdministered(totalCovishieldAdministered);
        setTotalSputnikVAdministered(totalSputnikVAdministered);
        setAefi(aefi);
        setAge_18_45Years(age_18_45Years);
        setAge_45_60Years(age_45_60Years);
        setAge_60AboveYears(age_60AboveYears);
        setTotalIndividualsVaccinated(totalIndividualsVaccinated);
    }
}
