/*
 * This file is generated by jOOQ.
 */
package co.homelane.db.jooq;


import co.homelane.db.jooq.tables.CovidVaccineStatewise;
import co.homelane.db.jooq.tables.Covid_19India;
import co.homelane.db.jooq.tables.Statewisetestingdetails;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DefaultSchema extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>DEFAULT_SCHEMA</code>
     */
    public static final DefaultSchema DEFAULT_SCHEMA = new DefaultSchema();

    /**
     * The table <code>covid_19_india</code>.
     */
    public final Covid_19India COVID_19_INDIA = Covid_19India.COVID_19_INDIA;

    /**
     * The table <code>covid_vaccine_statewise</code>.
     */
    public final CovidVaccineStatewise COVID_VACCINE_STATEWISE = CovidVaccineStatewise.COVID_VACCINE_STATEWISE;

    /**
     * The table <code>statewisetestingdetails</code>.
     */
    public final Statewisetestingdetails STATEWISETESTINGDETAILS = Statewisetestingdetails.STATEWISETESTINGDETAILS;

    /**
     * No further instances allowed
     */
    private DefaultSchema() {
        super("", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.<Table<?>>asList(
            Covid_19India.COVID_19_INDIA,
            CovidVaccineStatewise.COVID_VACCINE_STATEWISE,
            Statewisetestingdetails.STATEWISETESTINGDETAILS);
    }
}
