/*
 * This file is generated by jOOQ.
 */
package co.homelane.db.jooq;


import co.homelane.db.jooq.tables.CovidVaccineStatewise;
import co.homelane.db.jooq.tables.Covid_19India;
import co.homelane.db.jooq.tables.Statewisetestingdetails;


/**
 * Convenience access to all tables in the default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>covid_19_india</code>.
     */
    public static final Covid_19India COVID_19_INDIA = Covid_19India.COVID_19_INDIA;

    /**
     * The table <code>covid_vaccine_statewise</code>.
     */
    public static final CovidVaccineStatewise COVID_VACCINE_STATEWISE = CovidVaccineStatewise.COVID_VACCINE_STATEWISE;

    /**
     * The table <code>statewisetestingdetails</code>.
     */
    public static final Statewisetestingdetails STATEWISETESTINGDETAILS = Statewisetestingdetails.STATEWISETESTINGDETAILS;
}
